### ISSUE TITLE
很多百度pan无法访问了

### ISSUE THREAD

**Issue by SeekPoint** [FreedomIntelligence/Chinese_medical_NLP#1]

**Comment by lrs1353281004** [comment]
感谢提醒，我看了一下，应该只有语料资源的那个链接失效了，我后面重新更新一下。

**Comment by lrs1353281004** [comment]
感谢提醒，我看了一下，应该只有语料资源的那两个链接失效了，我后面重新更新一下。

**Comment by SeekPoint** [comment]
度盘下载地址：https://pan.baidu.com/s/1P2WHX7hNTqErZ3j1vhkr_Q

提取码：xd0c



度盘下载地址：https://pan.baidu.com/s/1NG8xybrEGTVYPepMM12xNw

提取码：mwmj

**Comment by lrs1353281004** [comment]
嗯嗯，就是这两个，我稍后找时间更新一下

**Comment by lrs1353281004** [comment]
hi  我看了一下   这两部资源是涉及侵权了，现在没办法在度盘中分享了，后续如果有其他开源渠道，我再更新

**Comment by SeekPoint** [comment]
我能不能私发我一份， yk_data@126.com

**Comment by lrs1353281004** [comment]
> 我能不能私发我一份， [yk_data@126.com](mailto:yk_data@126.com)

真的抱歉啊  当时的资料我传到网盘以后没有特意备份，昨晚找了一下没有找到 = = 没有考虑到网盘会挂掉这种情况，后面如果有精力我再找找别的更稳定的分享方式
